export enum ScreenNames {
  MAIN_TABS = 'MAIN_TABS',
  MAP_SCREEN = 'MAP_SCREEN',
  RATING_SCREEN = 'RATING_SCREEN',
  SAVED_SCREEN = 'SAVED_SCREEN',

  ONBOARDING_SCREEN = 'ONBOARDING_SCREEN',
  LOADING_SCREEN = 'LOADING_SCREEN',

  MAIN_STACK = 'MAIN_STACK',
  MAIN_SCREEN = 'MAIN_SCREEN',
  MAIN_SPINNER_SCREEN = 'MAIN_SPINNER_SCREEN',
  MAIN_LOADING_SCREEN = 'MAIN_LOADING_SCREEN',
  MAIN_SPINNER_RESULT_SCREEN = 'MAIN_SPINNER_RESULT_SCREEN',

  GAME_STACK = 'GAME_STACK',
  GAME_SCREEN = 'GAME_SCREEN',
  GAME_START_SCREEN = 'GAME_START_SCREEN',
}
